name: Daily Stranger Things Countdown

on:
  schedule:
    - cron: "0 8 * * *"  # Her gün öğlen 16:00 UTC (Türkiye'de 19:00)
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install tweepy
    - name: Run the bot
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: python bot.py
